#! python3
import requests as r
from bs4 import BeautifulSoup as bs
import webbrowser as w
c = 0#this is a counter for looping through the URL's in the list
li = []#records links to gaggia so that no repeats come up
URL = ['Put url here', 'here', 'and here']
for i in URL:#This cycles through the URL's
    page = r.get(URL[c])
    c+=1
    soup = bs(page.content, "html.parser")
    searc = soup.find(id="srp-river-main")#This selects all info on the page
    gaggia = searc.find_all("div", class_="s-item__info clearfix") #this defines the information for each item on the page
    g = 0 #this is useless but I needed put someting in the if statements below    
    for i in gaggia:
        itemname = i.find("h3", class_= "s-item__title")
        price = i.find("span", class_= "s-item__price")
        link = i.find("a", class_= "s-item__link")
        x = 'gaggia' and 'classic'
        y = 'to'
        if link["href"] not in li:          
            if x in itemname.text.lower(): 
                if price == None:
                    g+=1
                elif y in price.text.replace('$' ,''):
                    g+=1
                elif (float(price.text.replace('$','').replace(',','')) <= 200) and (float(price.text.replace('$','').replace(',','')) >=70):
                    print (itemname.text, end = "\n")
                    print (price.text, end = "\n")
                    li.append(link["href"])
                    w.open(link["href"])
